# Generated by Django 2.2.5 on 2019-09-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('claim_text', models.CharField(max_length=200)),
                ('special_text', models.CharField(max_length=200)),
                ('lp', models.IntegerField(default=0)),
                ('min_adv', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('persona', models.CharField(max_length=20)),
                ('active_value', models.IntegerField(default=0)),
                ('inactive_value', models.IntegerField(default=0)),
                ('inactive_used', models.BooleanField(default=True)),
                ('effect_text', models.CharField(max_length=400)),
                ('flavour_text', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
