# Generated by Django 2.2.5 on 2019-09-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardtemplateapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='id',
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
